### ISSUE TITLE
convert json-Ld to graphql schema

### ISSUE THREAD

**Issue by Rakeshjdev** [kbss-cvut/jopa-examples#3]
my requirement is to convert json-ld to graphql schema.if any body has a reference, please share with me. i will appreciate your help

**Comment by ledsoft** [comment]
I'm affraid I'm not very familiar with GraphQL. But you might take a look at [GraphQL-LD](https://comunica.github.io/Article-ISWC2018-Demo-GraphQlLD/).

**Comment by ledsoft** [comment]
Closing this one due to inactivity.
