### ISSUE TITLE
Failed to run

### ISSUE THREAD

**Issue by meroua** [kbss-cvut/jopa-examples#53]
I am trying to run example 2 using the command:
` mvn exec:java`

I got the following exception

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project example-02: An exception occured while executing the Java class. Illegal characte
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project example-02: An ex
ception occured while executing the Java class. Illegal character in authority at index 7: file://C:\Users\user\IdeaProjects\jopa-examples\example02-jopa-owlapi\repository.owl

**Comment by ledsoft** [comment]
Hi,
Thanks for reporting the issue. I suspect this is a problem of running the example on Windows, as I always tested it on Linux and it works. I will test it on a Windows machine and try to fix it.

**Comment by meroua** [comment]
Yes I am running on Windows.

**Comment by ledsoft** [comment]
Hi, should be fixed now. Feel free to reopen if the problem persists.
