### ISSUE TITLE
Logging does not work in example 2

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/jopa-examples#94]
I executed example 2 as stated in [README.md](https://github.com/kbss-cvut/jopa-examples/tree/master/example02-jopa-owlapi#running-the-demo) but i did not see any logging there:
![image](https://github.com/user-attachments/assets/50d8d505-e2ac-469b-b2fb-b368e30f09f1)

**Comment by ledsoft** [comment]
Thanks, fixed.
